class MetricsCollector:
    def on_arrival(self, router_id, packet, time): ...
    def on_enqueue(self, router_id, packet, time): ...
    def on_drop(self, router_id, packet, time): ...
    def on_forward(self, router_id, packet, next_hop, time): ...
    def on_deliver(self, packet, time): ...